matrix:
  include:
    # Java 8
    - language: java

      jdk: oraclejdk8

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

      before_install:
        - cd java
        - chmod +x gradlew

      script:
        - ./gradlew clean check

    # Java 9
    - language: java

      jdk: oraclejdk9

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

      before_install:
        - cd java
        - chmod +x gradlew

      script:
        - ./gradlew clean check

    - language: csharp

      solution: CSharp.sln

      mono: none
      dotnet: 1.1.5

      before_install:
        - cd csharp

      script:
        - dotnet restore
        - nuget restore CSharp.sln
        - msbuild /p:Configuration=Release CSharp.sln

